app:
  security:
    inactive-session-timeout: 10800000 # 3 * 60 * 60 - 3 hours
    max-token-ttl: 604800000 # 7 * 24 * 60 * 60 - 7 days
    jwt:
      key-store-resource: classpath:jwt-keystore.p12
      key-store-password: changeit
      key-alias: clockwork.tb.jwt
      key-password: changeit

spring:
  jpa:
    open-in-view: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: TableBooking
server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit

logging:
  level:
    org.clockwork: INFO
    org.clockwork.tablebooking.controller: DEBUG